
<?php
 // module/Album/view/album/album/index.phtml:
 $title = 'Jobs';
 $this->headTitle($title);
?>
       
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <h1 class="panel-heading"><?php echo $this->escapeHtml($title); ?></h1>     
            <span>
                <a  class="btn btn-primary" href="<?php echo $this->url('jobs', array('action'=>'add'));?>"> <?php echo $this->translate('Adicionar') ?></a>
            </span>

        </div>
    </div>
</div>
 <table class="table">
     <tr>
         <th> ID </th>
         <th>Titulo do Emprego</th>
         <td>&nbsp;</td>
     </tr>
         <?php foreach ($jobs as $job) : ?>
                            
            <tr>

                <td><?php echo $this->escapeHtml(preg_replace('/\s+/', '',$job->job_id));?></td> 
               <td><?php echo $this->escapeHtml($job->job_title);?></td> 
               <td>
                   <a class="btn btn-primary" href="<?php echo $this->url('jobs',
                       array('action'=>'edit', 'id' => preg_replace('/\s+/', '',$job->job_id) ));?>"> <?php echo $this->translate('Editar');?> </a>

                   <a  class="btn btn-danger" href="<?php echo $this->url('jobs',
                       array('action'=>'delete','id' => preg_replace('/\s+/', '',$job->job_id)));?>"> <?php echo $this->translate('Deletar');?> </a>
               </td>

           </tr>
                                                                            
        <?php endforeach; ?>
                                       
 </table>  