<?php

$title = 'Edição da Região de ID '.$this->id;
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<?php
// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('Regions',array('action' => 'edit','id' => $this->id)));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);

?>
<div class="hidden">
<?php
    $name = $form->get('region_id');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?></div>

<div class="form-group">
<?php
    $regionName = $form->get('region_name');
    
    
    
    echo $this->formInput($regionName);
    echo $this->formElementErrors($regionName);
    
    
?></div>

<?php echo $this->formElement($form->get('submit')) ?>
<a class="btn btn-info" href="<?php echo $this->url('Regions', array('action'=>'index'));?>">Cancel</a>
<?php echo $this->form()->closeTag() ?>


