<?php

$title = 'Formulário de Cadastro de Novos Endereços';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<?php
// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('Locations',array('action' => 'add')));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');
?>

<div class="form">

<?php echo $this->form()->openTag($form); ?>



<div class="form-group">
<?php
    $name = $form->get('location_id');
    
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>

<div class="form-group">
<?php
    $streetAddress = $form->get('street_address');

    echo $this->formInput($streetAddress);
    echo $this->formElementErrors($streetAddress);
?>
</div>
<div class="form-group">
<?php
    $postalCode = $form->get('postal_code');

    echo $this->formInput($postalCode);
    echo $this->formElementErrors($postalCode);
?>
</div>
<div class="form-group">
<?php
    $city = $form->get('city');

    echo $this->formInput($city);
    echo $this->formElementErrors($city);
?>
</div>
<div class="form-group">
<?php
    $stateProvince = $form->get('state_province');

    echo $this->formInput($stateProvince);
    echo $this->formElementErrors($stateProvince);
?>
</div>

<div class="form-group">
<?php
    $countryId = $form->get('country_id');

    echo $this->formElement($countryId);
    echo $this->formElementErrors($countryId);
?>

</div>

<?php if(!empty($this->error)): ?>
<div class="form-group">

    <div class="alert alert-danger">
        <?php echo $this->error; ?>
    </div>
</div>
<?php endif; ?>


<?php echo $this->formElement($form->get('submit')) ?>
    
<a class="btn btn-info" href="<?php echo $this->url('Locations', array('action'=>'index'));?>">Cancelar</a>

</div>
 <?php echo $this->form()->closeTag() ?>
