 <?php
 

 $title = 'Deletar Departamento '.$this->departments->department_id;
 $this->headTitle($title);
 

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="panel">
     <p class="panel-title">
         você realmente deseja excluir o departamento <strong><?php echo $this->departments->department_name; ?></strong>
     </p>
 </div>
 
 <?php
 $url = $this->url('departments', array(
     'action' => 'delete',
     'id'     => $this->departments->department_id,
     
 ));

 ?>
  <form action="<?php echo $url; ?>" method="post">
    <div class="form-group hidden">
        <input type="hidden" name="id" value="<?php echo (int) $this->departments->department_id; ?>" />
     </div>
        
     <div class="form-group">
         <input class="form-control btn btn-danger" type="submit" name="del" value="Yes" /> 
     </div>
     <div class="form-group">
         <input class="form-control btn btn-primary"type="submit" name="del" value="No" />
     </div>
 </form>