
 <?php
 
 $title = 'Funcionários';
 $this->headTitle($title);
?>
       
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <h1 class="panel-heading"><?php echo $this->escapeHtml($title); ?></h1>               
                <strong>
                            <a class="btn btn-primary" href="<?php echo $this->url('employees', array('action'=>'add'));?>"> <?php echo 'Adicionar' ?></a>
                </strong>
        </div>
    </div>
</div>
 <table class="table table-hover">
     <tr>
         <th> ID </th>
         <th>Nome</th>
         <th>Emprego</th>
         <th>Departamento</th>
         
         <td>&nbsp;</td>
     </tr>
     
         <?php foreach ($employees as $employee) : ?>
            
            <tr>
                
               <td><?php echo $this->escapeHtml($employee->employee_id);?></td> 
               <td><?php echo $this->escapeHtml($employee->full_name);?></td> 
               <td><?php echo $this->escapeHtml($employee->job_title);?></td>
               <td><?php echo $this->escapeHtml($employee->department_name);?></td>
               
               <td>
                   <a class="btn btn-info" href="<?php echo $this->url('employees',
                       array('action'=>'details','id' => $employee->employee_id));?>"> <?php echo $this->translate('Detalhes');?> </a>
                   <a class="btn btn-warning" href="<?php echo $this->url('employees',
                       array('action'=>'edit','id' => $employee->employee_id));?>"> <?php echo $this->translate('Editar');?> </a>
                       
                   <a  class="btn btn-danger" href="<?php echo $this->url('employees',
                       array('action'=>'delete', 'id' => $employee->employee_id));?>"> <?php echo $this->translate('Deletar');?> </a>
               </td>
               
           </tr>
        
        <?php endforeach; ?>
   
                                       
 </table> 
 <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
            // the paginator object
            $this->employees,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            'partial/paginator.phtml',
            // the route to link to when a user clicks a control link
            $this->route
        );
    ?>
 
 
 
 
 