 <?php
 

 $title = 'Deletar País '.$this->country->country_id;
 $this->headTitle($title);
 

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="panel">
     <p class="panel-title">
        você realmente deseja excluir a região <?php echo $this->country->country_name; ?>
     </p>
 </div>
 
 <?php
 $url = $this->url('countries', array(
     'action' => 'delete',
     'id'     => $this->country->country_id,
     
 ));

 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div
     <div class="form-group hidden">
         <input type="hidden" name="id" value="<?php echo (int) $this->country->country_id; ?>" />
     </div>
        
     <div class="form-group">
         <input class="form-control btn btn-danger" type="submit" name="del" value="Yes" /> 
     </div>
     <div class="form-group">
         <input class="form-control btn btn-primary"type="submit" name="del" value="No" />
     </div>
     
     
 </div>
 </form>