
<div class="jumbotron">
    <h1 class="">
        Recursos Humanos
    </h1>
    <p>
        Selecione uma das opções abaixo
    </p>
</div>
<div class="container">
    <div class="row panel">
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a href="<?php echo $this->url('employees', array('action'=>'index'));?>" class="btn btn-primary" title="New Employees"><img class="img" src="img/employee.jpg"></a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a href="<?php echo $this->url('jobs', array('action'=>'index'));?>" class="btn btn-primary" title="New Jobs"><img class="img" src="img/job.jpg"></a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a href="<?php echo $this->url('Locations', array('action'=>'index'));?>" class="btn btn-primary" title="New Locations"><img class="img" src="img/location.jpg"></a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a href="<?php echo $this->url('Regions', array('action'=>'index'));?>" class="btn btn-primary" title="New Regions"><img class="img" src="img/region.jpg"></a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a href="<?php echo $this->url('departments', array('action'=>'index'));?>" class="btn btn-primary" title="New Departments"><img class="img" src="img/department.jpg"></a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a href="<?php echo $this->url('countries', array('action'=>'index'));?>" class="btn btn-primary" title="New Countries"><img class="img" src="img/countries.png"></a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6 panel">
            <a  href="<?php echo $this->url('jobshistory', array('action'=>'index'));?>" class=" btn btn-primary " title="Job History"><img class="img" src="img/jobhistory.jpg"></a>
        </div>
    </div>    
        
        
        
        
        
    
</div>    